name: Daily Windy Data Fetch

on:
  schedule:
    - cron: "0 */3 * * *"  # every 3 hours, on the hour
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install requests pandas
      - name: Run script
        run: python windyAPI.py
      - name: Commit results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add precip.json windy_forecast_*.csv || true
          git commit -m "Update precipitation data $(date -u +"%Y-%m-%d_%H-%M-%S")" || true
          git push
